# Copyright Â© Advanced Micro Devices, Inc., or its affiliates.
#
# SPDX-License-Identifier: MIT

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "{{ .Release.Name }}-cnpg-superuser"
  namespace: "{{ .Release.Namespace }}"
  annotations:
    helm.sh/hook: pre-install
spec:
  data:
    - remoteRef:
        key: aiwb-cnpg-superuser-username
        property: value
      secretKey: username
    - remoteRef:
        key: aiwb-cnpg-superuser-password
        property: value
      secretKey: password
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.aiwb.externalSecretStore.aiwb.name }}
  target:
    name: "{{ .Release.Name }}-cnpg-superuser"
    template:
      type: Opaque
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "{{ .Release.Name }}-cnpg-user"
  namespace: "{{ .Release.Namespace }}"
  annotations:
    helm.sh/hook: pre-install
spec:
  data:
    - remoteRef:
        key: aiwb-cnpg-user-username
        property: value
      secretKey: username
    - remoteRef:
        key: aiwb-cnpg-user-password
        property: value
      secretKey: password
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.aiwb.externalSecretStore.aiwb.name }}
  target:
    name: "{{ .Release.Name }}-cnpg-user"
    template:
      type: Opaque
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "{{ .Release.Name }}-keycloak-client"
  namespace: "{{ .Release.Namespace }}"
  annotations:
    helm.sh/hook: pre-install
spec:
  data:
    - remoteRef:
        key: aiwb-keycloak-client-secret
        property: value
      secretKey: client-secret
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.aiwb.externalSecretStore.keycloak.name }}
  target:
    name: "{{ .Release.Name }}-keycloak-client"
    template:
      type: Opaque
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "{{ .Release.Name }}-api-minio-credentials"
  namespace: "{{ .Release.Namespace }}"
  annotations:
    helm.sh/hook: pre-install
spec:
  data:
    - remoteRef:
        key: aiwb-minio-access-key
        property: value
      secretKey: minio-access-key
    - remoteRef:
        key: aiwb-minio-secret-key
        property: value
      secretKey: minio-secret-key
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.aiwb.externalSecretStore.minio.name }}
  target:
    name: "{{ .Release.Name }}-api-minio-credentials"
    template:
      type: Opaque
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "{{ .Release.Name }}-cluster-auth-admin"
  namespace: "{{ .Release.Namespace }}"
  annotations:
    helm.sh/hook: pre-install
spec:
  data:
    - remoteRef:
        key: aiwb-cluster-auth-admin-token
        property: value
      secretKey: admin-token
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.aiwb.externalSecretStore.clusterAuth.name }}
  target:
    name: "{{ .Release.Name }}-cluster-auth-admin"
    template:
      type: Opaque
