# Copyright Â© Advanced Micro Devices, Inc., or its affiliates.
#
# SPDX-License-Identifier: MIT

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: '{{ .Release.Name }}api-route'
  namespace: '{{ .Release.Namespace }}'
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: {{ .Values.kgateway.gatewayName }}
      namespace: {{ .Values.kgateway.namespace }}
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: '{{ .Release.Name }}-api'
          port: {{ .Values.kgateway.aiwbapi.servicePort }}
          weight: 1
      matches:
        - headers:
            - name: Host
              type: RegularExpression
              value: {{ .Values.kgateway.aiwbapi.prefixValue }}\..*
          path:
            type: PathPrefix
            value: /
      timeouts:
        backendRequest: {{ .Values.kgateway.aiwbapi.timeouts.backendRequest }}
        request: {{ .Values.kgateway.aiwbapi.timeouts.request }}
