# Copyright Â© Advanced Micro Devices, Inc., or its affiliates.
#
# SPDX-License-Identifier: MIT

apiVersion: aim.silogen.ai/v1alpha1
kind: AIMClusterModel
metadata:
  name: aim-qwen-qwen3-32b-0-8-2-preview
spec:
  image: ghcr.io/silogen/aim-qwen-qwen3-32b:0.8.2-preview
---
apiVersion: aim.silogen.ai/v1alpha1
kind: AIMClusterModel
metadata:
  name: aim-mistralai-mixtral-8x7b-instruct-v0-1-0-8-2-preview
spec:
  image: ghcr.io/silogen/aim-mistralai-mixtral-8x7b-instruct-v0-1:0.8.2-preview
---
apiVersion: aim.silogen.ai/v1alpha1
kind: AIMClusterModel
metadata:
  name: aim-mistralai-mixtral-8x22b-instruct-v0-1-0-8-2-preview
spec:
  image: ghcr.io/silogen/aim-mistralai-mixtral-8x22b-instruct-v0-1:0.8.2-preview
---
apiVersion: aim.silogen.ai/v1alpha1
kind: AIMClusterModel
metadata:
  name: aim-mistralai-mistral-large-instruct-2411-0-8-2-preview
spec:
  image: ghcr.io/silogen/aim-mistralai-mistral-large-instruct-2411:0.8.2-preview
---
apiVersion: aim.silogen.ai/v1alpha1
kind: AIMClusterModel
metadata:
  name: aim-meta-llama-llama-3-3-70b-instruct-0-8-2-preview
spec:
  image: ghcr.io/silogen/aim-meta-llama-llama-3-3-70b-instruct:0.8.2-preview
---
apiVersion: aim.silogen.ai/v1alpha1
kind: AIMClusterModel
metadata:
  name: aim-meta-llama-llama-3-2-3b-instruct-0-8-2-preview
spec:
  image: ghcr.io/silogen/aim-meta-llama-llama-3-2-3b-instruct:0.8.2-preview
---
apiVersion: aim.silogen.ai/v1alpha1
kind: AIMClusterModel
metadata:
  name: aim-meta-llama-llama-3-2-1b-instruct-0-8-2-preview
spec:
  image: ghcr.io/silogen/aim-meta-llama-llama-3-2-1b-instruct:0.8.2-preview
---
apiVersion: aim.silogen.ai/v1alpha1
kind: AIMClusterModel
metadata:
  name: aim-meta-llama-llama-3-1-405b-instruct-0-8-2-preview
spec:
  image: ghcr.io/silogen/aim-meta-llama-llama-3-1-405b-instruct:0.8.2-preview
---
apiVersion: aim.silogen.ai/v1alpha1
kind: AIMClusterModel
metadata:
  name: aim-meta-llama-llama-3-1-8b-instruct-0-8-2-preview
spec:
  image: ghcr.io/silogen/aim-meta-llama-llama-3-1-8b-instruct:0.8.2-preview
---
apiVersion: aim.silogen.ai/v1alpha1
kind: AIMClusterModel
metadata:
  name: aim-tinyllama-tinyllama-1-1b-chat-v1-0-0-8-4-preview
spec:
  image: ghcr.io/silogen/aim-tinyllama-tinyllama-1-1b-chat-v1-0:0.8.4-preview
---
apiVersion: aim.silogen.ai/v1alpha1
kind: AIMClusterModel
metadata:
  name: aim-qwen-qwen3-8b-0-8-2-preview
spec:
  image: ghcr.io/silogen/aim-qwen-qwen3-8b:0.8.2-preview
---
apiVersion: aim.silogen.ai/v1alpha1
kind: AIMClusterModel
metadata:
  name: aim-qwen-qwen3-4b-0-8-2-preview
spec:
  image: ghcr.io/silogen/aim-qwen-qwen3-4b:0.8.2-preview
---
apiVersion: aim.silogen.ai/v1alpha1
kind: AIMClusterModel
metadata:
  name: aim-qwen-qwen3-30b-a3b-0-8-2-preview
spec:
  image: ghcr.io/silogen/aim-qwen-qwen3-30b-a3b:0.8.2-preview
---
apiVersion: aim.silogen.ai/v1alpha1
kind: AIMClusterModel
metadata:
  name: aim-qwen-qwen3-235b-a22b-0-8-2-preview
spec:
  image: ghcr.io/silogen/aim-qwen-qwen3-235b-a22b:0.8.2-preview
---
apiVersion: aim.silogen.ai/v1alpha1
kind: AIMClusterModel
metadata:
  name: aim-qwen-qwen3-14b-0-8-2-preview
spec:
  image: ghcr.io/silogen/aim-qwen-qwen3-14b:0.8.2-preview
---
apiVersion: aim.silogen.ai/v1alpha1
kind: AIMClusterModel
metadata:
  name: aim-qwen-qwen2-5-7b-instruct-0-8-2-preview
spec:
  image: ghcr.io/silogen/aim-qwen-qwen2-5-7b-instruct:0.8.2-preview
---
apiVersion: aim.silogen.ai/v1alpha1
kind: AIMClusterModel
metadata:
  name: aim-qwen-qwen2-5-3b-instruct-0-8-2-preview
spec:
  image: ghcr.io/silogen/aim-qwen-qwen2-5-3b-instruct:0.8.2-preview
---
apiVersion: aim.silogen.ai/v1alpha1
kind: AIMClusterModel
metadata:
  name: aim-qwen-qwen2-5-32b-instruct-0-8-2-preview
spec:
  image: ghcr.io/silogen/aim-qwen-qwen2-5-32b-instruct:0.8.2-preview
---
apiVersion: aim.silogen.ai/v1alpha1
kind: AIMClusterModel
metadata:
  name: aim-qwen-qwen2-5-14b-instruct-0-8-2-preview
spec:
  image: ghcr.io/silogen/aim-qwen-qwen2-5-14b-instruct:0.8.2-preview
---
apiVersion: aim.silogen.ai/v1alpha1
kind: AIMClusterModel
metadata:
  name: aim-qwen-qwen2-5-1-5b-instruct-0-8-2-preview
spec:
  image: ghcr.io/silogen/aim-qwen-qwen2-5-1-5b-instruct:0.8.2-preview
---
apiVersion: aim.silogen.ai/v1alpha1
kind: AIMClusterModel
metadata:
  name: aim-qwen-qwen2-5-0-5b-instruct-0-8-2-preview
spec:
  image: ghcr.io/silogen/aim-qwen-qwen2-5-0-5b-instruct:0.8.2-preview
---
apiVersion: aim.silogen.ai/v1alpha1
kind: AIMClusterModel
metadata:
  name: aim-cohereforai-aya-expanse-8b-0-8-2-preview
spec:
  image: ghcr.io/silogen/aim-cohereforai-aya-expanse-8b:0.8.2-preview
---
apiVersion: aim.silogen.ai/v1alpha1
kind: AIMClusterModel
metadata:
  name: aim-cohereforai-aya-expanse-32b-0-8-2-preview
spec:
  image: ghcr.io/silogen/aim-cohereforai-aya-expanse-32b:0.8.2-preview
---
apiVersion: aim.silogen.ai/v1alpha1
kind: AIMClusterModel
metadata:
  name: aim-mistralai-mistral-small-3-2-24b-instruct-2506-0-8-2-preview
spec:
  image: ghcr.io/silogen/aim-mistralai-mistral-small-3-2-24b-instruct-2506:0.8.2-preview
