# samall|medium|large (injected by bootstrap script)
clusterSize: null

# Domain for the cluster (injected by bootstrap script)
# Example: "compute.company.com"
domain: null

# Git revision to deploy (injected by bootstrap script)
targetRevision: null