{{- if .Values.rbacHelpers.enable }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    labels:
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/name: aim-engine
    name: aim-engine-aimclusterruntimeconfig-admin-role
rules:
    - apiGroups:
        - aim.eai.amd.com
      resources:
        - aimclusterruntimeconfigs
      verbs:
        - '*'
    - apiGroups:
        - aim.eai.amd.com
      resources:
        - aimclusterruntimeconfigs/status
      verbs:
        - get
{{- end }}
