# Copyright Â© Advanced Micro Devices, Inc., or its affiliates.
#
# SPDX-License-Identifier: MIT

apiVersion: aim.silogen.ai/v1alpha1
kind: AIMClusterModel
metadata:
  name: aim-meta-llama-llama-3-1-8b-instruct-0-7-0
spec:
  image: ghcr.io/silogen/aim-meta-llama-llama-3-1-8b-instruct:0.7.0
---
apiVersion: aim.silogen.ai/v1alpha1
kind: AIMClusterModel
metadata:
  name: aim-qwen-qwen3-4b-0-7-0-preview
spec:
  image: ghcr.io/silogen/aim-qwen-qwen3-4b:0.7.0-preview
