tenant:
  name: default-minio-tenant
  configSecret:
    name: default-minio-tenant-env-configuration
    existingSecret: true
  pools:
    - servers: 1
      name: pool-0
      volumesPerServer: 1
      size: 500Gi
      storageClassName: direct
  buckets:
    - name: default-bucket
      objectLock: true
    - name: models
      objectLock: true
  users:
    - name: default-user
  certificate:
    requestAutoCert: false
    externalCaCertSecret:
    - name: cluster-tls
      type: kubernetes.io/secret/v1
  env:
    - name: MINIO_PROMETHEUS_AUTH_TYPE
      value: "public"
